ifeq (eng,$(TARGET_BUILD_VARIANT))
VENDOR_LOG_LEVEL=I
SPAM_LOG_LEVEL=I
else
VENDOR_LOG_LEVEL=E
SPAM_LOG_LEVEL=F
endif

VENDOR_LOG_TAGS += \
    RILMUXD \
    RfxMclDisThread \
    RfxCloneMgr \
    RfxHandlerMgr \
    RfxIdToStr \
    RfxDisThread \
    RfxMclStatusMgr \
    RIL-Fusion \
    RilOemClient \
    RtcEccNumberController \
    RmcEccNumberUrcHandler \
    RfxMclDisThread \
    RfxCloneMgr \
    RfxHandlerMgr \
    RfxIdToStr \
    RfxDisThread \
    RfxMclStatusMgr \
    RIL-Fusion \
    RfxOpUtils \
    RfxMclMessenger \
    RfxFragEnc \
    RfxStatusMgr \
    RfxContFactory \
    RfxChannelMgr \
    RfxIdToMsgId \
    RtcDC \
    RmcDcCommon \
    RmcPhbReq \
    RmcPhbUrc \
    RtcPhb \
    RtcIms \
    RtcImsConfigController \
    RtcImsConference \
    RtcImsDialog \
    RmcImsCtlUrcHdl \
    RmcImsCtlReqHdl \
    RmcEmbmsReq \
    RmcEmbmsUrc \
    RtcEmbmsUtil \
    RtcEmbmsAt \
    RTC_DAC \
    RmcCommSimReq \
    RmcCdmaSimRequest \
    RmcGsmSimRequest \
    RmcCommSimUrc \
    RmcGsmSimUrc \
    RtcCommSimCtrl \
    RmcCommSimOpReq \
    RtcRadioCont \
    RmcDcPdnManager \
    RmcDcReqHandler \
    RmcDcUtility \
    RmcNwHdlr \
    RmcNwReqHdlr \
    RmcNwRTReqHdlr \
    RmcRatSwHdlr \
    RtcRatSwCtrl \
    RtcNwCtrl \
    RmcRadioReq \
    RmcCapa \
    RtcCapa \
    RtcWp \
    RmcWp \
    RmcOpRadioReq \
    RmcCdmaSimUrc \
    RmcOemHandler \
    RtcModeCont \
    AT \
    RILC \
    RfxMainThread \
    RfxRoot \
    RfxRilAdapter \
    RfxController \
    RilOpProxy \
    RILC-OP \
    WpfaCcciDataHeaderEncoder \
    WpfaCcciReader \
    WpfaCcciSender \
    WpfaControlMsgHandler \
    WpfaDriver \
    WpfaDriverAccept \
    WpfaDriverAdapter \
    WpfaDriverDeReg \
    WpfaDriverMessage \
    WpfaDriverRegFilter \
    WpfaDriverULIpPkt \
    WpfaDriverUtilis \
    WpfaDriverVersion \
    WpfaFilterRuleReqHandler \
    WpfaRingBuffer \
    WpfaShmAccessController \
    WpfaShmReadMsgHandler \
    WpfaShmSynchronizer \
    WpfaShmWriteMsgHandler \
    wpfa_iptable_android \
    WpfaRuleRegister \
    WpfaParsing \
    WpfaRuleContainer \
    MtkDct \
    MtkDc \
    MtkDcc \
    MtkRetryManager \
    DcFcMgr \
    NetAgentService \
    NetAgent_IO \
    NetLnkEventHdlr \
    C2K_RIL-DATA \
    GsmCdmaPhone \
    RILMD2-SS \
    CapaSwitch \
    DSSelector \
    DSSelectorOm \
    DSSelectorOP01 \
    DSSelectorOP02 \
    DSSelectorOP09 \
    DSSelectorOP18 \
    DSSelectorUtil \
    SimSwitchOP01 \
    SimSwitchOP02 \
    SimSwitchOP18 \
    IccProvider \
    IccPhoneBookIM \
    AdnRecordCache \
    AdnRecordLoader \
    AdnRecord \
    MtkIccProvider \
    MtkIccPHBIM \
    MtkAdnRecord \
    MtkRecordLoader \
    VT \
    ImsVTProvider \
    IccCardProxy \
    IsimFileHandler \
    IsimRecords \
    SIMRecords \
    SpnOverride \
    UiccCard \
    UiccController \
    CountryDetector \
    NetworkStats \
    NetworkPolicy \
    DataDispatcher \
    ImsService \
    IMS_RILA \
    IMSRILRequest \
    ImsManager \
    ImsApp \
    ImsBaseCommands \
    MtkImsManager \
    MtkImsService \
    ImsCall \
    ImsPhone \
    ImsPhoneCall \
    ImsPhoneBase \
    ImsCallSession \
    ImsCallProfile \
    ImsEcbm \
    ImsEcbmProxy \
    OperatorUtils \
    WfoApp \
    GsmCdmaConn \
    GsmCdmaPhone \
    Phone \
    GsmCallTkrHlpr \
    MtkPhoneNotifr \
    MtkFactory \
    MtkGsmCdmaConn \
    RadioManager \
    RIL \
    RIL_UIM_SOCKET \
    RILD \
    RfxMessage \
    RfxDebugInfo \
    RfxTimer \
    RfxObject \
    SlotQueueEntry \
    RfxAction \
    RFX \
    PhoneFactory \
    ProxyController \
    SpnOverride \
    AirplaneHandler \
    ExternalSimMgr \
    VsimAdaptor \
    MtkCsimFH \
    MtkIsimFH \
    MtkRuimFH \
    MtkSIMFH \
    MtkSIMRecords \
    MtkSmsCbHeader \
    MtkSmsManager \
    MtkSmsMessage \
    MtkSpnOverride \
    MtkIccCardProxy \
    MtkUiccCard \
    MtkUiccCardApp \
    MtkUiccCtrl \
    MtkUsimFH \
    MtkSubCtrl \
    MtkEmbmsAdaptor \
    RilClient \
    RfxRilAdapter \
    MTKSST \
    RfxRilUtils \
    WORLDMODE \
    MtkPhoneNumberUtils \
    MtkPhoneSwitcher \
    RIL-Parcel \
    RIL-Socket \
    RIL-SocListen \
    RIL-Netlink \
    MwiRIL \
    PQ_DS \
    CarrierExpressServiceImpl \
    CarrierExpressServiceImplExt \
    PhoneConfigurationSettings \
    DMC-Core \
    DMC-TranslatorLoader \
    DMC-TranslatorUtils \
    DMC-ReqQManager \
    DMC-DmcService \
    DMC-ApmService \
    DMC-SessionManager \
    DMC-EventsSubscriber \
    LCM-Subscriber \
    APM-Subscriber \
    MDM-Subscriber \
    APM-SessionJ \
    APM-SessionN \
    APM-ServiceJ \
    APM-KpiMonitor \
    PKM-MDM \
    PKM-Lib \
    PKM-Monitor \
    PKM-SA \
    PKM-Service \
    MAPI-TranslatorManager \
    MAPI-MdiRedirectorCtrl \
    MAPI-MdiRedirector \
    MAPI-NetworkSocketConnection \
    MAPI-SocketConnection \
    MAPI-SocketListener \
    MAPI-CommandProcessor \
    libPowerHal \
    mtkpower@impl \
    mtkpower_client \
    UxUtility \
    PowerHalAddressUitls \
    PowerHalMgrImpl \
    PowerHalMgrServiceImpl \
    PowerHalWifiMonitor \
    gralloc4 \
    HWUI \
    FrameTracker \
    C2MtkBufferManager \
    libsensor-client2css \
    libperfmgr \
    android.hardware.graphics.composer@2.3-service \
    libcitsensorservice@2.0-impl \
    HfLooper

SPAM_LOG_TAGS := \
    libsensor-frameBufferManager \
    libsensor-displayInfoManager \
    libsensor-displayalgo \
    libsensor-parseRGB \
    libsensor-ssccalapi \
    hwcomposer

PRODUCT_VENDOR_PROPERTIES += \
    $(foreach tag,$(SPAM_LOG_TAGS),log.tag.$(tag)=$(SPAM_LOG_LEVEL)) \
    $(foreach tag,$(VENDOR_LOG_TAGS),log.tag.$(tag)=$(VENDOR_LOG_LEVEL))

ifneq (eng,$(TARGET_BUILD_VARIANT))
PRODUCT_VENDOR_PROPERTIES += \
    log.tag=W
endif

